
// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;


internal class Program
{
    private static void Main(string[] args)
    {
        Console.WriteLine("İlk sayıyı giriniz      :");
        int ilksayi = Convert.ToInt32(Console.ReadLine());

        Console.WriteLine("İkinci sayıyı giriniz   :");
        int ikincisayi = Convert.ToInt32(Console.ReadLine());

        Console.WriteLine("Üçüncü sayıyı giriniz   :");
        int ucuncusayi = Convert.ToInt32(Console.ReadLine());

        if (ilksayi < ikincisayi && ilksayi > ucuncusayi || ilksayi > ikincisayi && ilksayi < ucuncusayi)
            Console.WriteLine("{0} sayısı ortanca sayıdır.", ilksayi);

        else if (ikincisayi < ilksayi && ikincisayi > ucuncusayi || ikincisayi > ilksayi && ikincisayi < ucuncusayi)
            Console.WriteLine("{0} sayısı ortanca sayıdır.", ikincisayi);
        else if (ucuncusayi < ilksayi && ucuncusayi > ikincisayi || ucuncusayi > ilksayi && ucuncusayi < ikincisayi)
            Console.WriteLine("{0} sayısı ortanca sayıdır.", ucuncusayi);
        else
            Console.WriteLine("En az iki sayı birbirine eşit olduğundan ortanca sayı tespiti yapılamaz." );


        Console.ReadKey();  





        Console.WriteLine("Hello, World!");
    }
}